apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
  namespace: default
spec:
  selector:
    matchLabels:
      app: chatbot
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: matkimchi/chatbot:15
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service 
  labels:
    app: chatbot
spec:
  selector:
    app: chatbot
  ports:
  - port: 9080
    name: http

