name: Build and Push Chatbot service

on:
  push:
    paths:
      - 'chatbot/**'

jobs:
  build:
    runs-on: ubuntu-latest  
    outputs:
      TAG: ${{github.run_number}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./chatbot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot:${{github.run_number}}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max
  push:
    name: Push Manifests
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{needs.build.outputs.TAG}}
    steps:
      - name : Checkout repository
        uses: actions/checkout@v2

      - name: Change manifest
        run : sed -i "s|matkimchi/chatbot:[^ ]*|matkimchi/chatbot:${{env.TAG}}|" "k8s/application.yml"
      
      - name: git push
        run: |
          git config user.name "kyounghoonJang"
          git config user.email "matkimchi_@naver.com"
          git remote set-url origin "https://${{ secrets.GH_TOKEN }}@github.com/24-HI034/24-HI034-Backend.git"
          git add k8s/application.yml
          git commit -m "Update chatbot image"
          git push




    



      