name: Build and Push Chatbot service

on:
  push:
    paths:
      - 'chatbot/**'

jobs:
  build:
    runs-on: ubuntu-latest  
    outputs:
      TAG: ${{github.run_number}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./chatbot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot:${{github.run_number}}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max
  push:
    name: Push Manifests
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{needs.build.outputs.TAG}}
    steps:
      - name : Checkout repository
        uses: actions/checkout@v2

      - name: Change manifest
        run : sed -i "s|matkimchi/chatbot:[^ ]*|matkimchi/chatbot:${{env.TAG}}|" "k8s/application.yml"
      
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main




    



      